### ISSUE TITLE
Detached nodes after creation at different positions

### ISSUE THREAD

**Issue by JannikStreek** [b310-digital/teammapper#250]
**Describe the bug**
When a detached node is created, the position seems to be different on clients.

**To Reproduce**
1. Add a detached node
2. Compare position with different joined clients
3. After moving the node, positions are synced properly

**Expected behavior**
Position should be the same, even in the beginning.

**Screenshots**

**Comment by sorenjohanson** [comment]
Core issue seems to be this:

When a new detached node is created (for example based off of the root node), it's coordinates are set to 0,0 (x,y) in mmp.service.ts#221. The same method then calls addNode, which adds -80 to y coordinates at nodes.ts#620, presumably to prevent overlap. This is all done client-side. At this point, the node is saved server side and the other client receives it. However, the other client calls the same method at nodes.ts#620 and adds _another_ -80 to y coordinates (again, to prevent overlap), causing the coordinates to be 0,-160 instead of 0,-80.
